#pragma once

enum Stats
{
  STAT_POWER,
  STAT_DEFENSE,
  STAT_TOUGHNESS,
  STAT_VITALITY,
  STAT_PRECISION,
  STAT_FEROCITY,
  STAT_CONDITION_DAMAGE_BASE,
  STAT_EXPERTISE,
  STAT_CONCENTRATION,
  STAT_HEALING_POWER,
  STAT_AGONY_RESISTANCE,
  NUM_BASE_STATS,
  
  STAT_ARMOR = NUM_BASE_STATS,
  STAT_MAX_HEALTH,
  NUM_INTEGRAL_STATS,
  
  STAT_CRITICAL_CHANCE = NUM_INTEGRAL_STATS,
  STAT_CRITICAL_DAMAGE,
  NUM_STATS
};
