#pragma once

enum BoonIndex
{
    BOON_AEGIS,
    BOON_FURY,
    BOON_MIGHT,
    BOON_PROTECTION,
    BOON_QUICKNESS,
    BOON_REGENERATION,
    BOON_RESISTANCE,
    BOON_RETALIATION,
    BOON_STABILITY,
    BOON_SWIFTNESS,
    BOON_VIGOR,
    NUM_BOONS
};

enum ConditionIndex
{
    CONDI_BLEEDING,
    CONDI_BURNING,
    CONDI_CONFUSION,
    CONDI_POISON,
    CONDI_TORMENT,
    CONDI_BLIND,
    CONDI_CHILLED,
    CONDI_CRIPPLED,
    CONDI_FEAR,
    CONDI_IMMOBILIZED,
    CONDI_SLOW,
    CONDI_TAUNT,
    CONDI_WEAKNESS,
    CONDI_VULNERABILITY,
    NUM_CONDITIONS
};
